name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:

    runs-on: macos-latest

    strategy:
      matrix:
        run-config:
          - { scheme: 'GithubActionsTestApp', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary




