name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Swift Test
      run: swift test
      env:
          DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer





